---
 log_level: "info"
 file_info:
   input_knowledge_base_files: # A list of all files to combine into the knowledge base
    - "scasp_knowledge_base/knowledge_base_virtualhome_v2.pl"
    - "scasp_knowledge_base/analogy_knowledge.pl"
    - "scasp_knowledge_base/vh_task_list.pl"
#    - "scasp_knowledge_base/generated_vh_task_list_modified_singletons.pl"
   final_knowledge_base_file: "scasp_knowledge_base/generated_kb.pl" # Name of the combined kb
 vecsr_settings:
  use_real_simulator: True # Real simulator or not?
  run_dynamically: False # Run dynamically or not?
  use_answer_key: False # Use an answer key or not?
  step_by_step: False # Get plans step by step or not?
  counterfactual_analysis: False # Counterfactual analysis?
  take_actions_in_sim: False # Actually take actions in simulation?
  optimizations: # Optimizations from VECSR debut in ICLP 2025
    dependency_graph: False # Optimize by dependency graph or not?
    partial_ground: True # Partially ground to remove unnecessary items or not?
    modules: False # Only use relevant modules/rooms or not?
  tasks: # Note: Multiple tasks is only supported on MacOS currently
    - "read"
# Test Set
#   - "add_paper_to_printer"
#   - "admire_art"
#   - "answer_door"
#   - "answer_emails"
#   - "answer_phone"
#   - "arrange_furniture"
#   - "arrange_shoes"
#   - "arrange_sofa"
#   - "brew_coffee"
#   - "bring_leftovers_in_kitchen"
#   - "bring_me_red_cookbook"
#   - "build_lego_house"
#   - "call_client"
#   - "call_family_member_with_skype_application"
#   - "call_mother"
#   - "card"
#   - "care_for_houseplants"
#   - "carry_groceries_to_kitchen"
#   - "change_tv_channels"
#   - "change_bedding"
#   - "change_sheets_and_pillow_cases"
#   - "change_sheets_on_bed"
#   - "change_shower_curtain"
#   - "change_toilet_paper_roll"
#   - "change_toothbrush"
#   - "check_appearance_in_mirror"
#   - "clean_glasses"
#   - "clean_large_jacuzzi_tub"
#   - "clean_screen"
#   - "close_curtains"
#   - "close_shower_curtain"
#   - "collect_napkin_rings"
#   - "color"
#   - "come_home"
#   - "complete_surveys_on_amazon_turk"
#   - "comput"
#   - "computer_work"
#   - "cut_bread"
#   - "cut_toenails"
#   - "cutting"
#   - "dance_for_table_as_we_eat"
#   - "dewrinkle_sheet"
#   - "designing_crafts_with_family"
#   - "do_freestyle_dance_routine"
#   - "do_work"
#   - "do_work_on_computer"
#   - "do_yoga"
#   - "dry_soap_bottles"
#   - "eat_ice_cream"
#   - "eat_while_watching_tv"
#   - "enter_home"
#   - "fan_magazines_on_coffee_table"
#   - "feed_dog"
#   - "find_dictionary"
#   - "fix_bowl_of_cereal"
#   - "fix_sandwich"
#   - "fix_snack"
#   - "gaze_out_window"
#   - "get_in_way_of_guests_trying_to_leave"
#   - "get_mail_ready"
#   - "get_ready_for_bed"
#   - "get_ready_for_day"
#   - "get_ready_for_school"
#   - "get_ready_to_leave"
#   - "get_something_to_drink"
#   - "give_children_bath"
#   - "give_me_bath"
#   - "give_your_child_bath"
#   - "go_to_bathroom"
#   - "grab_some_juice"
#   - "grab_things"
#   - "hang_car_keys"
#   - "hang_keys"
#   - "hang_pictures"
#   - "hang_up_car_keys"
#   - "hang_up_poster"
#   - "have_dinner"
#   - "have_ice_coffee"
#   - "have_party"
#   - "have_tea_party"
#   - "help_kids_with_homework"
#   - "help_with_quiz_shows"
#   - "hold_coats_and_umbrellas"
#   - "juggling"
#   - "keep_cats_out_of_room"
#   - "leave_home"
#   - "light_candle"
#   - "light_candles"
#   - "look_at_mirror"
#   - "look_at_painting"
#   - "make_banana_bread"
#   - "make_iced_coffee"
#   - "make_kids_bed"
#   - "make_peanut_butter_sandwich"
#   - "make_phone_call"
#   - "make_place_cards"
#   - "make_popcorn"
#   - "make_tomato_sauce"
#   - "make_tutu"
#   - "make_up_bed_for_guest_on_couch"
#   - "manage_documents"
#   - "manage_emails"
#   - "oil_dining_room"
#   - "open_bathroom_window"
#   - "open_door_and_great_guests"
#   - "open_window"
#   - "order_office_suplies"
#   - "organize_files"
#   - "organize_pantry"
#   - "paint_ceiling"
#   - "peel_kiwi"
#   - "peel_potatoes"
#   - "pick_toys"
#   - "pick_up_all_trash"
#   - "pick_up_cat_hair"
#   - "pick_up_dishes"
#   - "pick_up_spare_change_on_dresser"
#   - "place_bathmat"
#   - "place_centerpiece"
#   - "place_table"
#   - "play_fetch_with_dog"
#   - "play_on_laptop"
#   - "play_piano"
#   - "play_with_toys"
#   - "playtime_lunch_with_dolls"
#   - "plug_in_nightlight"
#   - "polish_table"
#   - "polish_tea_pot"
#   - "pour_cup_of_coffee"
#   - "praying"
#   - "print_out_document"
#   - "push_all_chairs_in"
#   - "push_in_desk_chair"
#   - "push_in_dining_room_chair"
#   - "put_alarm_clock_in_bedroom"
#   - "put_away_blankets"
#   - "put_away_clothes"
#   - "put_away_dishes"
#   - "put_away_jackets"
#   - "put_away_keys"
#   - "put_down_bags"
   - "put_in_chair"
#   - "put_mail_away"
#   - "put_on_coat_and_shoes"
#   - "put_out_flowers"
#   - "put_shoes_and_coats"
#   - "put_shoes_in_shoe_rack"
#   - "put_slippers_in_closet"
#   - "put_up_feet"
#   - "put_washed_clothes_in_almirah"
#   - "rain_welcome"
#   - "raise_blinds"
#   - "read_magazine"
#   - "read_text_message"
#   - "recycle_items"
#   - "replace_toothpaste"
#   - "replace_towel"
#   - "restock"
#   - "return_from_store"
#   - "return_phone_calls"
#   - "rotate_stock_in_refrigerator"
#   - "say_goodbye"
#   - "say_goodbye_to_guests_leaving"
#   - "scrub_bottom_of_feet"
#   - "scrubbing_living_room_tile_floor_is_once_week_activity_for_me"
#   - "serve_cookies"
#   - "serve_food"
#   - "serve_meal"
#   - "set_up_tv"
#   - "shredding"
#   - "shut_off_alarm"
#   - "sing_karaoke"
#   - "sing_song"
#   - "sit_in_chair"
#   - "slice_apple"
#   - "sort_and_fold_laundry"
#   - "sort_clothing_and_care_for_it"
#   - "sort_laundry"
#   - "spend_family_time_playing_games"
#   - "squeeze_lemon"
#   - "straighten_bookshelf"
#   - "straighten_pictures_on_wall"
#   - "surf_internet"
#   - "surf_net"
#   - "surf_web_for_money_legitimate_making_opportunities"
#   - "sweep_hallway_please"
#   - "switch_on_lamp"
#   - "take_off_coat"
#   - "take_shoes_off"
#   - "tax_filing"
#   - "text_friend"
#   - "throw_away_newspaper"
#   - "throw_away_paper"
#   - "toast_bread"
#   - "turn_off_tv"
#   - "turn_on_tv"
#   - "turn_on_radio"
#   - "use_laptop"
#   - "wash_and_clean_all_crystal_in_china_cabinet"
#   - "wash_back"
#   - "wash_dining_table"
#   - "wash_monitor"
#   - "wash_table"
#   - "water_plants"
#   - "wipe_down_baseboards_please"
#   - "wipe_room_down_with_lysol"
#   - "write"
#   - "write_report"
#   - "practice_own_singing"
#   - "use_bathroom"
#   - "vacuum_carpet"
# Success
   # Training Tasks
#   - "play_games"
#   - "toilet"
#   - "read_newspaper"
#   - "browse_computer"
#   - "prepare_sandwich"
#   - "write_book"
#   - "lay_tablecloth"
#   - "prepare_letter_for_mailing"
#   - "settle_in"
#   - "ignore_people"
#   - "sort_mail"
#   - "tidy"
#   - "pop_zit"
#   - "load_dishwasher"
#   - "go_pee"
#   - "broom"
#   - "pull_up_carpet"
#   - "get_out_dish"
#   - "put_on_foundation"
#   - "turking"
#   - "take_jacket_off"
#   - "get_drink"
#   - "social_media__checks"
#   - "cook_some_food"
#   - "clean_sink"
#   - "clean"
#   - "get_some_water"
#   - "wash_hair"
#   - "take_coat"
#   - "wipe_feet"
#   - "shred_receipts"
#   - "take_dishes_out_of_dishwasher"
#   - "organize"
#   - "greet_guests"
#   - "defrost_chicken"
#   - "decorate"
#   - "clean_eggs_from_our_chickens"
#   - "watch_youtube"
#   - "clean_kitchen"
#   - "sit_quietly"
#   - "clean_floor"
#   - "complete_homework"
#   - "break_table"
#   - "answer_door"
#   - "arrange_bookshelf"
#   - "shampoo_hair"
#   - "wash_hands"
#   - "dress_up_and_pretend"
#   - "write_story"
#   - "watch_fly"
#   - "pee"
#   - "wash_dishes"
#   - "do_dishes"
#   - "make_tea"
#   - "make_sandwich"
#   - "cut_steak"
#   - "talk_with_friends"
#   - "talk_with_guest"
#   - "wipe_off_shoes"
#   - "unload_various_items_from_pockets_and_place_them_in_bowl_on_table"
#   - "type_up_document"
#   - "put_on_your_shoes"
#   - "put_groceries_in_fridge"
#   - "watch_movie"
#   - "put_away_shoes"
#   - "put_up_coat"
#   - "read"
#   - "read_to_child"
#   - "pick_up_phone"
#   - "wash_clothes"
#   - "workout"
#   - "dance"
#   - "read_yourself_to_sleep"
#   - "write_in_your_diary"
#   - "wave_at_people_walking_by_through_window"
#   - "sweep_and_wipe_table_off_with_rag"
#   - "receive_credit_card"
#   - "rearrange_photo_frames"
#   - "hang_out"
#   - "fluff_pillows"
#   - "style_hair"
#   - "dust"
#   - "dance_with_kids"
#   - "shave"
#   - "put_on_purse_put_keys_and_lucky_charms_in_pockets_leave_home"
#   - "work"
#   - "chop_vegetables"
#   - "use_toilet"
#   - "hand_washing"
#   - "put_on_coat"
#   - "take_nap"
#   - "get_glass_of_water"
#   - "deficate"
#   - "scrub_toilet"
#   - "talk_with_your_child_about_their_day"
#   - "wipe_down_counter"
#   - "tell_jokes"
#   - "put_dishes_away"
#   - "bring_dirty_plate_to_sink"
#   - "eat_snacks_and_drink_tea"
#   - "get_toilet_paper"
#   - "relax"
#   - "get_glass_of_milk"
#   - "put_up_jacket"
#   - "wash_face"
#   - "play_guitar"
#   - "added_meat_to_freezer"
#   - "make_coffee"
#   - "cut_your_hair"
#   - "read_book"
#   - "polishing_floor"
#   - "research"
#   - "brush_teeth"
#   - "turn_on_computer"
#   - "do_nails"
#   - "hides"
#   - "bathe"
#   - "grading_papers"
#   - "clear_table"
#   - "mop_floor"
#   - "talk_to_kids"
#   - "play_musical_chairs"
#   - "physical_therapy"
#   - "meeting"
#   - "brush_hair"
#   - "hair_dressing"
#   - "try_yourself_off"
#   - "use_bathroom"
#   - "arrange_folders"
#   - "mop"
#   - "prepare_dinner"
#   - "breakfast"
#   - "listen_to_music"
#   - "start_computer"
#   - "bake"
#   - "make_eggs"
#   - "sit"
#   - "go_to_bed"
#   - "put_away_clean_clothes"
#   - "turn_on_tv_with_remote"
#   - "put_away_groceries"
#   - "wake_kids_up"
#   - "whine"
#   - "homework"
#   - "lay_down_on_floor_and_say_im_rug"
#   - "flush_toilet"
#   - "clean_mirror"
#   - "visit"
#   - "relax_on_sofa"
#   - "pick_up"
#   - "study_bible"
#   - "tuck_kids_in_bed"
#   - "change_curtains"
#   - "eat_cheese"
#   - "enjoy_view_out_window"
#   - "change_tv_channel"
#   - "pretend_tea"
#   - "steam_mop_floor"
#   - "vacuum"
#   - "laugh"
#   - "sweep_floor"
#   - "hair"
#   - "speaking_on_headset_in_skype_or_some_form_of_voip_for_business_call"
#   - "change_clothes"
#   - "open_curtains"
#   - "eat_cereal"
#   - "put_up_decoration"
#   - "put_clothes_away"
#   - "clean_toilet"
#   - "look_out_window"
#   - "read_on_sofa"
#   - "transcribe_what_i_say"
#   - "let_baby_learn_how_to_walk"
#   - "do_an_art_project"
#   - "wait"
#   - "print_out_papers"
#   - "organise_paperwork"
#   - "look_in_refrigerator"
#   - "get_ready_for_work"
#   - "hang_up_jacket"
#   - "fix_broken_toys"
#   - "pull_hair_out_of_drain"
#   - "wash_teeth"
#   - "take_off_shoes"
#   - "wash_sink"
#   - "give_milk_to_cat"
#   - "have_conversation_with_boyfriend"
#   - "send__email"
#   - "clean_bathroom"
#   - "pick_up_toys"
#   - "set_up_table"
#   - "re_arrange_office"
#   - "tale_off_shoes"
#   - "practice_violin"
#   - "keep_cats_inside_while_door_is_open"
#   - "get_dressed"
#   - "wash_dirty_dishes"
#   - "do_laundry"
#   - "read_them_bedtime_story"
#   - "organize_closet"
#   - "do_taxes"
#   - "read_news"
#   - "scrub_face"
#   - "watch_tv"
#   - "bring_food"
#   - "do_facial"
#   - "complete_school_work"
#   - "write_letter"
#   - "visit_neighbors"
#   - "make_childs_bed"
#   - "close_dresser_drawer"
#   - "sleep"
#   - "massage"
#   - "put_mail_in_mail_organizer"
#   - "organize_desk"
#   - "make_toast"
#   - "pick_up_obvious_trash"
#   - "put_dvds_on_shelves"
#   - "story_reading_time"
#   - "teach_them_to_make_their_bed"
#   - "put_toys_away"
#   - "comb_hair"
#   - "getting__dresses"
#   - "put_away_toys"
#   - "sent_email"
#   - "take_bath"
#   - "check_self_in_mirror"
#   - "make_several_copies_on_printer"
#   - "throw_shoes"
#   - "write__school_paper"
#   - "keep_an_eye_on_stove_as_something_is_cooking"
#   - "turn_light_off"
#   - "face_washing"
#   - "check_email"
#   - "dry_hair"
#   - "put_umbrella_away"
#   - "iron_shirt"
#   - "spread_table_with_appropriate_supplies"
#   - "apply_lotion"
#   - "write_an_email"
#   - "shoe_removal"
#   - "pick_up_dirty_dishes"
#   - "curled_hair"
#   - "prepare_pot_of_boiling_water"
#   - "put_on_glasses"
#   - "stretch"
#   - "pet_cat"
#   - "pet_dog"
#   - "turn_off_light"
#   - "make_drink"
#   - "playing_video_game"
#   - "movie"
#   - "come_in_and_leave_home"
#   - "wake_me_up"
#   - "make_ice_in_ice_trays_for_freezer"
#   - "make_jello"
#   - "drink"
#   - "set_mail_on_table"
#   - "go_to_toilet"
#   - "make_bed"
#   - "turn_on_light"
#   - "put_new_books_in_shelves"
#   - "take_shower"
#   - "check_homework"
#   - "annoy_your_dog"
#   - "straighten_magazines"
#   - "tummy_time"
#   - "yoga"
#   - "write_research_paper"
#   - "draw_picture"
#   - "sew"
#   - "read_paper"
#   - "turn_night_light_on"
#   - "go_to_sleep"
#   - "study"
#   - "write_thank_you_notes"
#   - "shop"
#   - "file_expense_reports"
#   - "take_off_outerwear"
#   - "pack_lunch"
#   - "unload_dishwasher"
#   - "sew_button"
#   - "greet_people"
#   - "use_restroom"
#   - "decorate_it"
#   - "mail_signed_letter_to_customer"
#   - "fax_forms_to_doctor"
#   - "eat_donuts"
#   - "talk_on_phone"
#   - "print_documents"
#   - "clean_dishes"
#   - "family_meetings"
#   - "play"
#   - "prepare_for_work"
#   - "tabletop_game"
#   - "visit_with_friends_while_engaging_in_games"
#   - "put_up_towel"
#   - "set_up_buffet_area"
#   - "change_light"
#   - "update_address_book"
#   - "thanksgiving"
#   - "put_them_to_sleep"
#   - "set_out_some_snacks_for_toddler"
#   - "sweep_entrance_hall"
#   - "make__cookies"
#   - "string_green_beans"
#   - "clean_room"
#   - "play_with_barbies"
#   - "file_documents"
#   - "do_homework"
#   - "fold_laundry"
#   - "exercise"
#   - "serve_hors_doeuvres_to_entering_guests_at_cocktail_party"
#   - "paint_nails"
#   - "hang_with_friends"
#   - "help_organize_files"
#   - "empty_dishwasher_and_fill_dishwasher"
#   - "polish_your_shoes"
#   - "draft_home"
#   - "use_computer"
#   - "browse_internet"
#   - "pay_bills"
#   - "entertain"
#   - "eat_family_meals"
#   - "have_snack"
#   - "prepare_breakfast"
#   - "eat_on_fancy_china"
#   - "make_cereal"
#   - "celebrate"
#   - "have_quality_family_time"
#   - "text_friends_while_sitting_on_couch"
#   - "dining"
#   - "clean_fridge"
#   - "eat_meals"
#   - "in_living_room_i_eat_dinner"
#   - "eat"
#   - "feed_me"
#   - "eat_dessert"
#   - "eat_dinner"
#   - "celebrate_birthday_with_nice_meal"
 vecsra_settings:
   scasp_client: # If using as s(CASP) client machine, set to true and include the IP Address for the s(CASP) server
     enabled: True
     ip_address: "192.168.1.135"
   task: "loc(70,0,-10)" # Task for drone, currently only able to be set to a location to navigate to
